# Generated by Django 4.2.6 on 2023-10-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0002_alter_genere_genere_alter_track_name_alter_track_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genere',
            name='track_id',
        ),
        migrations.CreateModel(
            name='Trackgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundback.genere')),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundback.track')),
            ],
        ),
    ]
