# Generated by Django 4.2.6 on 2023-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0003_remove_genere_track_id_trackgen'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(to='soundback.genere'),
        ),
        migrations.DeleteModel(
            name='Trackgen',
        ),
    ]
