# Generated by Django 4.2.6 on 2023-10-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0004_track_genres_delete_trackgen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genres',
            new_name='generes',
        ),
    ]
