# Generated by Django 4.2.6 on 2023-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0005_rename_genres_track_generes'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='show',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
