# Generated by Django 4.2.6 on 2023-10-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0007_alter_genere_genere'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genere',
            unique_together={('genere',)},
        ),
    ]
