# Generated by Django 4.2.6 on 2023-10-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0008_alter_genere_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genere',
            unique_together=set(),
        ),
    ]
