# Generated by Django 4.2.6 on 2023-10-19 13:36

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0009_alter_genere_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genere',
            name='genere',
            field=models.CharField(max_length=50, unique=True, verbose_name='genere'),
        ),
        migrations.AddConstraint(
            model_name='genere',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('genere'), name='unique_upper_genere_category'),
        ),
    ]
