# Generated by Django 4.2.6 on 2023-10-19 14:21

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('soundback', '0011_remove_genere_unique_upper_genere_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genere',
            name='unique_lower_genere_category',
        ),
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AddConstraint(
            model_name='genere',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('genere'), name='Genere already exists'),
        ),
    ]
